import { registerAs } from '@nestjs/config';

export default registerAs('app', () => ({
  nodeEnv: process.env.NODE_ENV ?? 'development',
  port: Number(process.env.PORT ?? 3000),
  apiPrefix: process.env.API_PREFIX ?? 'api/v1',
  corsOrigins: process.env.CORS_ORIGINS ?? 'http://localhost:5173,http://127.0.0.1:5173',
  appName: process.env.APP_NAME ?? 'Enterprise Blog API',
  jwtAccessSecret: process.env.JWT_ACCESS_SECRET ?? 'change-me-access-secret',
  jwtRefreshSecret: process.env.JWT_REFRESH_SECRET ?? 'change-me-refresh-secret',
  commentCaptchaSecret: process.env.COMMENT_CAPTCHA_SECRET ?? 'change-me-comment-captcha-secret',
  jwtAccessExpiresIn: process.env.JWT_ACCESS_EXPIRES_IN ?? '1d',
  jwtAccessExpiresInSeconds: Number(process.env.JWT_ACCESS_EXPIRES_IN_SECONDS ?? 86400),
  bcryptSaltRounds: Number(process.env.BCRYPT_SALT_ROUNDS ?? 12),
  storageProvider: process.env.STORAGE_PROVIDER ?? 'LOCAL',
  storageBucket: process.env.STORAGE_BUCKET ?? 'enterprise-blog',
  storagePublicBaseUrl: process.env.STORAGE_PUBLIC_BASE_URL ?? '',
  storageUploadDir: process.env.STORAGE_UPLOAD_DIR ?? '',
  storageSignedExpiresInSeconds: Number(process.env.STORAGE_SIGNED_EXPIRES_IN_SECONDS ?? 900),
  s3Region: process.env.S3_REGION ?? '',
  s3Endpoint: process.env.S3_ENDPOINT ?? '',
  s3AccessKeyId: process.env.S3_ACCESS_KEY_ID ?? '',
  s3SecretAccessKey: process.env.S3_SECRET_ACCESS_KEY ?? '',
  s3SessionToken: process.env.S3_SESSION_TOKEN ?? '',
  s3ForcePathStyle: process.env.S3_FORCE_PATH_STYLE ?? 'false',
  mailEnabled: process.env.MAIL_ENABLED ?? 'false',
  mailProvider: process.env.MAIL_PROVIDER ?? 'SMTP',
  mailFromName: process.env.MAIL_FROM_NAME ?? 'Enterprise Blog',
  mailFromAddress: process.env.MAIL_FROM_ADDRESS ?? '',
  mailSmtpHost: process.env.MAIL_SMTP_HOST ?? '',
  mailSmtpPort: Number(process.env.MAIL_SMTP_PORT ?? 587),
  mailSmtpSecure: process.env.MAIL_SMTP_SECURE ?? 'false',
  mailSmtpUser: process.env.MAIL_SMTP_USER ?? '',
  mailSmtpPass: process.env.MAIL_SMTP_PASS ?? '',
  mailRetryCount: Number(process.env.MAIL_RETRY_COUNT ?? 3),
  mailRetryBackoffMs: Number(process.env.MAIL_RETRY_BACKOFF_MS ?? 800),
  staticOutputDir: process.env.STATIC_OUTPUT_DIR ?? './static-export',
  backupOutputDir: process.env.BACKUP_OUTPUT_DIR ?? './backups',
  opsConfirmSecret: process.env.OPS_CONFIRM_SECRET ?? '',
  opsConfirmTtlSeconds: Number(process.env.OPS_CONFIRM_TTL_SECONDS ?? 900),
  loginCaptchaSecret: process.env.LOGIN_CAPTCHA_SECRET ?? 'change-me-login-captcha-secret',
  loginMaxFailures: Number(process.env.LOGIN_MAX_FAILURES ?? 5),
  loginBlockMinutes: Number(process.env.LOGIN_BLOCK_MINUTES ?? 15),
  rateLimitPerMinute: Number(process.env.RATE_LIMIT_PER_MINUTE ?? 180),
  ccBurstThreshold: Number(process.env.CC_BURST_THRESHOLD ?? 80),
  ccBurstWindowSeconds: Number(process.env.CC_BURST_WINDOW_SECONDS ?? 10),
  ccAutoBanMinutes: Number(process.env.CC_AUTO_BAN_MINUTES ?? 10),
  securityLoginAlertEmailEnabled: process.env.SECURITY_LOGIN_ALERT_EMAIL_ENABLED ?? 'false',
  enforceHttps: process.env.ENFORCE_HTTPS ?? 'false',
  redisUrl: process.env.REDIS_URL ?? '',
  redisKeyPrefix: process.env.REDIS_KEY_PREFIX ?? 'enterprise_blog',
  redisHealthProbeIntervalSeconds: Number(process.env.REDIS_HEALTH_PROBE_INTERVAL_SECONDS ?? 60),
  redisDegradedAlertThrottleSeconds: Number(process.env.REDIS_DEGRADED_ALERT_THROTTLE_SECONDS ?? 900),
  redisSlaWindowHours: Number(process.env.REDIS_SLA_WINDOW_HOURS ?? 24),
  securityProbeAlertEmailEnabled: process.env.SECURITY_PROBE_ALERT_EMAIL_ENABLED ?? 'false',
  geoipEnabled: process.env.GEOIP_ENABLED ?? 'true',
  geoipLicenseKey: process.env.GEOIP_LICENSE_KEY ?? '',
  geoipAutoUpdateIntervalHours: Number(process.env.GEOIP_AUTO_UPDATE_INTERVAL_HOURS ?? 24),
}));
